CONFIG_ZMK_POINTING=y
CONFIG_ZMK_PM_SOFT_OFF=y
CONFIG_ZMK_KEYBOARD_NAME="s10pao_crkbd"
CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_DISPLAY=y
CONFIG_ZMK_DISPLAY_BLANK_ON_IDLE=y
CONFIG_ZMK_IDLE_TIMEOUT=15000
CONFIG_ZMK_BATTERY_REPORTING=y
CONFIG_ZMK_BATTERY_REPORT_INTERVAL=300
