# Copyright 2022 Manna Harbour
# https://github.com/manna-harbour/miryoku

name: 'Build Example corne nice_nano_v2 nice_view'
on: workflow_dispatch
jobs:
  build:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      board: '["nice_nano_v2"]'
      shield: '["corne_left nice_view_adapter nice_view","corne_right nice_view_adapter nice_view"]'
      # shield: '["corne_left nice_view_adapter nice_view","corne_right nice_view_adapter nice_view","settings_reset"]'
      branches: '["s10pao-na-special/zmk/v0.3"]'
      clipboard: '["win"]'
      kconfig: '["CONFIG_ZMK_POINTING=y\nCONFIG_ZMK_PM_SOFT_OFF=y\nCONFIG_ZMK_KEYBOARD_NAME=\\\"s10pao_crkbd\\\"\nCONFIG_ZMK_SLEEP=y\nCONFIG_ZMK_IDLE_SLEEP_TIMEOUT=3600000"]'
      custom_config: '["#define MIRYOKU_KLUDGE_SOFT_OFF\n#define MIRYOKU_KLUDGE_GLOBALSHIFTFUNCTIONS"]'
